version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/maven
  maven: circleci/maven@1.4.1

executors:
  openjdk21:
    docker:
      # https://circleci.com/developer/ja/images/image/cimg/openjdk
      - image: cimg/openjdk:21.0

workflows:
  verify:
    jobs:
      - maven/test:
          name: test
          executor: openjdk21
          command: '-e verify sonar:sonar'
