spring:
  application:
    name: protobuf-demo-client
  main:
    banner-mode: off
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus
